spark = " искра \n       "
speed_boots = "скоростные\nботинки   "
radio = "  радио  \n         "
chaos_emerald = " изумруд \n  хаоса  "
remote_robot = " меха  \n тейлз "
hammer = " молоток \n         "
remote_bomb = "удаленная\n  бомба  "
rocket_booster = "ракетный  \nускоритель"
helmet = "  шлем  \n        "
teleport_device = "гаджет   \nтелепорта"
super_glove = "супер   \nперчатка"
mine = "  мина  \n        "
napalm_bomb = "напалмовая\nбомба     "
anti_air_missile = "зенитная\nракета  "
triple_bomb = "тройная \nбомба   "
sonic = " соник \n       "
proton_torpedo = "протонная\n торпеда "
extra_speed = "ускорение\n         "
night_vision = " ночное  \n видение "
item_radar = "предметный\nрадар     "
fang = "  фэнг  \n        "
large_bomb = " крупная \n бомба   "
extra_armor = "неуязвимость\n            "
wrench = "гаечный\nключ   "
knuckles = "  наклз  \n         "

