regular_bomb = "обычная бомба"
triple_bomb = "тройная бомба"
large_bomb = "крупная бомба"
wrench = "гаечный ключ"
remote_bomb = "удаленная бомба"
helmet = "шлем"
napalm_bomb = "напалмовая бомба"
remote_robot = "меха тейлз"
hammer = "молоток"
super_glove = "супер перчатка"
teleport_device = "гаджет телепорта"
fang = "фэнг"
night_vision = "ночное видение"
knuckles = "наклз"
speed_boots = "скоростн. ботинки"
sonic = "соник"
item_radar = "предметный радар"
radio = "радио"

purple_emerald = "фиолет.изумруд х."
red_emerald = "красн. изумруд х."
blue_emerald = "синий изумруд х."
white_emerald = "белый изумруд х."
green_emerald = "зелен. изумруд х."
yellow_emerald = "желтый изумруд х."

vulcan_gun = "вулканич. пушка"
anti_air_missile = "зенитная ракета"
proton_torpedo = "протонная торпеда"
spark = "искра"
extra_speed = "ускорение"
mine = "мина"
extra_armor = "неуязвимость"
rocket_booster = "ракетный ускоритель"

