video = "графика"
controls = "управление"
sound = "звук"
on = "вкл"
off = "выкл"

resolution = "соотн. сторон"
pixel_ar = "рiхеl аr"
pixel_ar_gg = "gg"
scale_mode = "масштаб"
scale_mode_smooth = "гладкий"
scale_mode_sharp = "резкий"
vsync = "v-sуnс"
vsync_adapt = "адаптация"
window_size = "размер окна"

map_keyboard = "клавиатура"
map_gamepad = "геимпад"
rumble = "вибрация"
hide_onscreen = "прятать на экране"

button_up = "вверх"
button_down = "вниз"
button_left = "влево"
button_right = "вправо"
button_a = "а"
button_b = "в"
button_lb = "lв"
button_rb = "rв"
button_start = "sтаrт"

main = "общий"
music = "музыка"
sfx = "звук"

