battle_fortress = { x=172, y=42 }

main = [
	{ name=" дом  \n тейлза ", x=122, y=97, up=1, left=1, right=8 },
	{ name=" лес \n полой", path="maps/pf/pf1", x=106, y=89, up=5, down=0, left=6, right=2 },
	{ name="туннель\nвулкана", path="maps/vt/vt1", x=146, y=73, up=3, down=0, left=1, right=9 },
	{ name="гора \nполли 1", path="maps/pm/pm1", x=146, y=41, up=4, down=2, left=7, right=4 },
	{ name="пещерный\nостров  ", path="maps/ci/ci1", x=182, y=33, left=3, down=8, right=9 },
	{ name=" лес \n кэрон", path="maps/cf/cf1", x=106, y=49, down=1, left=6, right=7 },
	{ name="зеленый\nостров", path="maps/gi/gi1", x=70, y=57, down=1, right=5 },
	{ name="гора \nполли 2", path="maps/pv/pv1", x=122, y=41, down=0, left=5, right=3 },
	{ name=" остров \n коко   ", path="maps/cc/cc1", x=178, y=105, up=4, left=0, right=9 },
	{ name="крепость\nбитвы   ", path="maps/bf/bf3", battle_fortress=true, x=197, y=52, up=4, down=8, left=2 },
]

seafox = [
	{ name=" дом  \n теилза ", highlight=false, x=122, y=88, down=1, up=2, right=2 },
	{ name=" озеро \n рокки", highlight=false, path="maps/lr/lr1", x=131, y=111, up=0, left=0, right=3 },
	{ name="озеро \nкристалл", path="maps/lc/lc1", highlight=false, x=135, y=79, up=3, down=1, left=0, right=3 },
	{ name="крепость\nбитвы   ", path="maps/bf/bf1", battle_fortress=true, x=185, y=60, down=1, left=2 },
]